# IMAGE SETTINGS
IMAGE_WIDTH=400
IMAGE_HEIGHT=300
TEXT_SIZE=32
TEXT_COLOR=(0, 255, 0) # Green
BACKGROUND_COLOR=(255, 255, 255) # White

# IMAGE COMPARISION SETTINGS
DISSIMILARITY_THRESHOLD=5 # x>=0; 0 is EXACTLY the same, perceptually
# PERCEPTUAL HASH COMPUTATION SETTINGS
HASH_SIZE=16
HIGHFREQ_FACTOR=8
